const API_KEY = process.env.CRYPTO_API_KEY

export async function GET(request: Request) {
  // const url = new URL(request.url)
  // const params = new URLSearchParams(url.search)
  // const ids = params.get('ids')

  // const response = await fetch(`https://pro-api.coinmarketcap.com/v2/cryptocurrency/info?id=${ids}`, {
  //   headers: {
  //     'X-CMC_PRO_API_KEY': API_KEY!,
  //   },
  // })

  // const res = await response.json()
  // return Response.json(res.data)
  return Response.json(data)
}

const data = {
  '1': {
    category: 'coin',
    contract_address: [],
    date_added: '2010-07-13T00:00:00.000Z',
    date_launched: '2010-07-13T00:00:00.000Z',
    description:
      'Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,697,290. The last known price of Bitcoin is 61,183.33842317 USD and is up 0.89 over the last 24 hours. It is currently trading on 11041 active market(s) with $13,064,037,149.51 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
    id: 1,
    infinite_supply: false,
    is_hidden: 0,
    logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1.png',
    name: 'Bitcoin',
    notice: '',
    platform: null,
    self_reported_circulating_supply: null,
    self_reported_market_cap: null,
    self_reported_tags: null,
    slug: 'bitcoin',
    subreddit: 'bitcoin',
    symbol: 'BTC',
    'tag-groups': [
      'OTHERS',
      'ALGORITHM',
      'ALGORITHM',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'PLATFORM',
      'CATEGORY',
    ],
    'tag-names': [
      'Mineable',
      'PoW',
      'SHA-256',
      'Store Of Value',
      'State Channel',
      'Coinbase Ventures Portfolio',
      'Three Arrows Capital Portfolio',
      'Polychain Capital Portfolio',
      'Binance Labs Portfolio',
      'Blockchain Capital Portfolio',
      'BoostVC Portfolio',
      'CMS Holdings Portfolio',
      'DCG Portfolio',
      'DragonFly Capital Portfolio',
      'Electric Capital Portfolio',
      'Fabric Ventures Portfolio',
      'Framework Ventures Portfolio',
      'Galaxy Digital Portfolio',
      'Huobi Capital Portfolio',
      'Alameda Research Portfolio',
      'a16z Portfolio',
      '1Confirmation Portfolio',
      'Winklevoss Capital Portfolio',
      'USV Portfolio',
      'Placeholder Ventures Portfolio',
      'Pantera Capital Portfolio',
      'Multicoin Capital Portfolio',
      'Paradigm Portfolio',
      'Bitcoin Ecosystem',
      'FTX Bankruptcy Estate ',
    ],
    tags: [
      'mineable',
      'pow',
      'sha-256',
      'store-of-value',
      'state-channel',
      'coinbase-ventures-portfolio',
      'three-arrows-capital-portfolio',
      'polychain-capital-portfolio',
      'binance-labs-portfolio',
      'blockchain-capital-portfolio',
      'boostvc-portfolio',
      'cms-holdings-portfolio',
      'dcg-portfolio',
      'dragonfly-capital-portfolio',
      'electric-capital-portfolio',
      'fabric-ventures-portfolio',
      'framework-ventures-portfolio',
      'galaxy-digital-portfolio',
      'huobi-capital-portfolio',
      'alameda-research-portfolio',
      'a16z-portfolio',
      '1confirmation-portfolio',
      'winklevoss-capital-portfolio',
      'usv-portfolio',
      'placeholder-ventures-portfolio',
      'pantera-capital-portfolio',
      'multicoin-capital-portfolio',
      'paradigm-portfolio',
      'bitcoin-ecosystem',
      'ftx-bankruptcy-estate',
    ],
    twitter_username: '',
    urls: {
      announcement: [Array],
      chat: [Array],
      explorer: [Array],
      facebook: [Array],
      message_board: [Array],
      reddit: [Array],
      source_code: [Array],
      technical_doc: [Array],
      twitter: [Array],
      website: [Array],
    },
  },
  '1027': {
    category: 'coin',
    contract_address: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    date_added: '2015-08-07T00:00:00.000Z',
    date_launched: null,
    description:
      'Ethereum (ETH) is a cryptocurrency . Ethereum has a current supply of 120,111,216.19093147. The last known price of Ethereum is 2,931.83768031 USD and is up 1.16 over the last 24 hours. It is currently trading on 8915 active market(s) with $6,164,563,177.64 traded over the last 24 hours. More information can be found at https://www.ethereum.org/.',
    id: 1027,
    infinite_supply: true,
    is_hidden: 0,
    logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
    name: 'Ethereum',
    notice: '',
    platform: null,
    self_reported_circulating_supply: null,
    self_reported_market_cap: null,
    self_reported_tags: null,
    slug: 'ethereum',
    subreddit: 'ethereum',
    symbol: 'ETH',
    'tag-groups': [
      'ALGORITHM',
      'CATEGORY',
      'PLATFORM',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'PLATFORM',
      'CATEGORY',
      'CATEGORY',
    ],
    'tag-names': [
      'PoS',
      'Smart Contracts',
      'Ethereum Ecosystem',
      'Coinbase Ventures Portfolio',
      'Three Arrows Capital Portfolio',
      'Polychain Capital Portfolio',
      'Binance Labs Portfolio',
      'Blockchain Capital Portfolio',
      'BoostVC Portfolio',
      'CMS Holdings Portfolio',
      'DCG Portfolio',
      'DragonFly Capital Portfolio',
      'Electric Capital Portfolio',
      'Fabric Ventures Portfolio',
      'Framework Ventures Portfolio',
      'Hashkey Capital Portfolio',
      'Kenetic Capital Portfolio',
      'Huobi Capital Portfolio',
      'Alameda Research Portfolio',
      'a16z Portfolio',
      '1Confirmation Portfolio',
      'Winklevoss Capital Portfolio',
      'USV Portfolio',
      'Placeholder Ventures Portfolio',
      'Pantera Capital Portfolio',
      'Multicoin Capital Portfolio',
      'Paradigm Portfolio',
      'Injective Ecosystem',
      'Layer 1',
      'FTX Bankruptcy Estate ',
    ],
    tags: [
      'pos',
      'smart-contracts',
      'ethereum-ecosystem',
      'coinbase-ventures-portfolio',
      'three-arrows-capital-portfolio',
      'polychain-capital-portfolio',
      'binance-labs-portfolio',
      'blockchain-capital-portfolio',
      'boostvc-portfolio',
      'cms-holdings-portfolio',
      'dcg-portfolio',
      'dragonfly-capital-portfolio',
      'electric-capital-portfolio',
      'fabric-ventures-portfolio',
      'framework-ventures-portfolio',
      'hashkey-capital-portfolio',
      'kenetic-capital-portfolio',
      'huobi-capital-portfolio',
      'alameda-research-portfolio',
      'a16z-portfolio',
      '1confirmation-portfolio',
      'winklevoss-capital-portfolio',
      'usv-portfolio',
      'placeholder-ventures-portfolio',
      'pantera-capital-portfolio',
      'multicoin-capital-portfolio',
      'paradigm-portfolio',
      'injective-ecosystem',
      'layer-1',
      'ftx-bankruptcy-estate',
    ],
    twitter_username: 'ethereum',
    urls: {
      announcement: [Array],
      chat: [Array],
      explorer: [Array],
      facebook: [Array],
      message_board: [Array],
      reddit: [Array],
      source_code: [Array],
      technical_doc: [Array],
      twitter: [Array],
      website: [Array],
    },
  },
  '1839': {
    category: 'coin',
    contract_address: [[Object]],
    date_added: '2017-07-25T00:00:00.000Z',
    date_launched: null,
    description:
      'BNB (BNB) is a cryptocurrency . BNB has a current supply of 147,586,873.85779196. The last known price of BNB is 593.81385691 USD and is up 0.86 over the last 24 hours. It is currently trading on 2155 active market(s) with $1,178,338,882.26 traded over the last 24 hours. More information can be found at https://bnbchain.org/en.',
    id: 1839,
    infinite_supply: false,
    is_hidden: 0,
    logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png',
    name: 'BNB',
    notice: '',
    platform: null,
    self_reported_circulating_supply: null,
    self_reported_market_cap: null,
    self_reported_tags: null,
    slug: 'bnb',
    subreddit: 'bnbchainofficial',
    symbol: 'BNB',
    'tag-groups': [
      'INDUSTRY',
      'CATEGORY',
      'INDUSTRY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'PLATFORM',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
    ],
    'tag-names': [
      'Marketplace',
      'Centralized Exchange (CEX) Token',
      'Payments',
      'Smart Contracts',
      'Alameda Research Portfolio',
      'Multicoin Capital Portfolio',
      'BNB Chain',
      'Layer 1',
      'SEC Security Token',
      'Alleged SEC Securities',
      'Celsius Bankruptcy Estate',
    ],
    tags: [
      'marketplace',
      'centralized-exchange',
      'payments',
      'smart-contracts',
      'alameda-research-portfolio',
      'multicoin-capital-portfolio',
      'bnb-chain',
      'layer-1',
      'sec-security-token',
      'alleged-sec-securities',
      'celsius-bankruptcy-estate',
    ],
    twitter_username: 'bnbchain',
    urls: {
      announcement: [Array],
      chat: [Array],
      explorer: [Array],
      facebook: [Array],
      message_board: [Array],
      reddit: [Array],
      source_code: [Array],
      technical_doc: [Array],
      twitter: [Array],
      website: [Array],
    },
  },
  '5426': {
    category: 'coin',
    contract_address: [],
    date_added: '2020-04-10T00:00:00.000Z',
    date_launched: '2020-03-16T00:00:00.000Z',
    description:
      'Solana (SOL) is a cryptocurrency launched in 2020. Solana has a current supply of 575,861,836.9931659 with 448,542,859.4607062 in circulation. The last known price of Solana is 145.49797325 USD and is up 0.96 over the last 24 hours. It is currently trading on 657 active market(s) with $1,016,347,747.11 traded over the last 24 hours. More information can be found at https://solana.com.',
    id: 5426,
    infinite_supply: true,
    is_hidden: 0,
    logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
    name: 'Solana',
    notice: '',
    platform: null,
    self_reported_circulating_supply: null,
    self_reported_market_cap: null,
    self_reported_tags: null,
    slug: 'solana',
    subreddit: 'solana',
    symbol: 'SOL',
    'tag-groups': [
      'ALGORITHM',
      'CATEGORY',
      'PLATFORM',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
      'CATEGORY',
    ],
    'tag-names': [
      'PoS',
      'Platform',
      'Solana Ecosystem',
      'CMS Holdings Portfolio',
      'Kenetic Capital Portfolio',
      'Alameda Research Portfolio',
      'Multicoin Capital Portfolio',
      'OKX Ventures Portfolio',
      'Layer 1',
      'FTX Bankruptcy Estate ',
      'SEC Security Token',
      'Alleged SEC Securities',
      'CMC Crypto Awards 2024',
    ],
    tags: [
      'pos',
      'platform',
      'solana-ecosystem',
      'cms-holdings-portfolio',
      'kenetic-capital-portfolio',
      'alameda-research-portfolio',
      'multicoin-capital-portfolio',
      'okx-ventures-portfolio',
      'layer-1',
      'ftx-bankruptcy-estate',
      'sec-security-token',
      'alleged-sec-securities',
      'cmc-crypto-awards-2024',
    ],
    twitter_username: 'solana',
    urls: {
      announcement: [Array],
      chat: [Array],
      explorer: [Array],
      facebook: [Array],
      message_board: [Array],
      reddit: [Array],
      source_code: [Array],
      technical_doc: [Array],
      twitter: [Array],
      website: [Array],
    },
  },
  '825': {
    category: 'token',
    contract_address: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
    date_added: '2015-02-25T00:00:00.000Z',
    date_launched: null,
    description:
      'Tether USDt (USDT) is a cryptocurrency and operates on the Ethereum platform. Tether USDt has a current supply of 113,086,550,460.89633 with 110,840,001,385.8282 in circulation. The last known price of Tether USDt is 0.99959038 USD and is up -0.00 over the last 24 hours. It is currently trading on 85152 active market(s) with $25,950,057,146.95 traded over the last 24 hours. More information can be found at https://tether.to.',
    id: 825,
    infinite_supply: true,
    is_hidden: 0,
    logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/825.png',
    name: 'Tether USDt',
    notice: '',
    platform: {
      id: '1027',
      name: 'Ethereum',
      slug: 'ethereum',
      symbol: 'ETH',
      token_address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
    },
    self_reported_circulating_supply: null,
    self_reported_market_cap: null,
    self_reported_tags: null,
    slug: 'tether',
    subreddit: '',
    symbol: 'USDT',
    'tag-groups': [
      'CATEGORY',
      'CATEGORY',
      'PLATFORM',
      'PLATFORM',
      'PLATFORM',
      'PLATFORM',
      'PLATFORM',
      'PLATFORM',
      'CATEGORY',
      'PLATFORM',
    ],
    'tag-names': [
      'Stablecoin',
      'Asset-Backed Stablecoin',
      'Avalanche Ecosystem',
      'Solana Ecosystem',
      'Arbitrum Ecosystem',
      'Moonriver Ecosystem',
      'Injective Ecosystem',
      'BNB Chain',
      'USD Stablecoin',
      'Optimism Ecosystem',
    ],
    tags: [
      'stablecoin',
      'asset-backed-stablecoin',
      'avalanche-ecosystem',
      'solana-ecosystem',
      'arbitrum-ecosytem',
      'moonriver-ecosystem',
      'injective-ecosystem',
      'bnb-chain',
      'usd-stablecoin',
      'optimism-ecosystem',
    ],
    twitter_username: 'tether_to',
    urls: {
      announcement: [Array],
      chat: [Array],
      explorer: [Array],
      facebook: [Array],
      message_board: [Array],
      reddit: [Array],
      source_code: [Array],
      technical_doc: [Array],
      twitter: [Array],
      website: [Array],
    },
  },
}
